/*startJson*/var locale_en = {
  "lean_business_builder": "Lean business builder",
  "canvas_header":"Lean business builder",
  "canvas_subheader":"Do you want to start a company, or just play around with some ideas? Start here!",
  "button_save": "Save",
  "tasks": "Tasks",
  "business_idea": "Business Idea",
  "gap": "GAP",
  "objectives": "Objectives",
  "business_model": "Business Model",
  "overview": "Overview",
  "resources": "Resources",
  "risks": "Risks",
  "title":"Title",
  "good_luck":"Good luck!",
  "label_idea_name": "idea name",
  "label_task_name": "Name of the task",
  "label_activity_name": "Name of the activity",
  "label_associated": "Associated",
  "label_status": "Status",
  "label_description": "Description",
  "label_responsible": "Responsible",
  "label_due_month": "Due month",
  "label_costgroup": "Cost group",
  "label_gap_name":"Name of gap",
  "label_obj_name":"Name of the objective",
  "label_risk_name":"Name of the risk",
  "label_objtype":"Objective type",
  "label_sum":"Sum",
  "label_cost":"Cost",
  "label_consequence":"Consequence",
  "label_probability": "Probability",
  "label_model_name": "Sticky title",
  "canvas_message_1":"You will build a business or just test out business ideas?",
  "canvas_message_2":"Need board a see what you are doing? Start here!",
  "done":"Done",
  "save":"Save",
  "business_ideas":"Business ideas",
  "model_header":"Business models",
  "model_subheader":"The business idea tell you what you should regarding your business. The business model will tell you how you should do it.",
  "modelItems_partners_header":"Who can help you?",
  "modelItems_partners_help":"Which partners and contacts can help you?",
  "modelItems_partners_placeholder":"Which partners and contacts can help you?",
  "modelItems_sell_header":"How will you sell?",
  "modelItems_sell_help":"Where and how will you sell your product? How will you market it?",
  "modelItems_sell_placeholder":"Where and how will you sell your product? How will you market it?",
  "modelItems_charge_header":"How will you charge?",
  "modelItems_charge_help":"What is your payment model?",
  "modelItems_charge_placeholder":"What is your payment model?",
  "modelItems_proposition_header":"What is your unique value proposition?",
  "modelItems_proposition_help":"What is your unique selling point? What will separate you from your competitors?",
  "modelItems_proposition_placeholder":"What is your unique selling point? What will separate you from your competitors?",
  "modelItems_product_header":"What will be your product?",
  "modelItems_product_help":"What will the customer get when buying your product?",
  "modelItems_product_placeholder":"What will the customer get when buying your product?",
  "modelItems_customers_header":"Who will be your first customers?",
  "modelItems_customers_help":"Name your first customers. Be specific!",
  "modelItems_customers_placeholder":"Name your first customers. Be specific!",
  "add_or_change":"Add or change",
  "expand":"Expand",
  "revenue_and_expenditure":"revenue and expenditure",
  "reply":"reply",
  "your_comment":"your comment",
  "comments":"comments",
  "this_section_can_be_skipped":"This section can be skipped if you do not think it provides value.",
  "instructions_header":"Owners instructions",
  "instructions_subheader":"What instructions do you get from the owners of the company? Do you own the company yourself? Do you have partners? Or do you have passive owners? Either way, you need to know what the owners want before you start planning.",
  "instructions_reason_header":"why did the owner(s) start the company?",
  "instructions_reason_help":"This is where you as an owner can describe your motivation for starting the company. It may be important for the employees to know the background of the company.",
  "instructions_reason_placeholder":"This is where you as an owner can describe your motivation for starting the company. It may be important for the employees to know the background of the company.",
  "instructions_values_header":"what is the owner(s) values?",
  "instructions_values_help":"Describe what values you as an owners think are important at a general level. These values will influence your judgments and decisions.",
  "instructions_values_placeholder":"Describe what values you as an owners think are important at a general level. These values will influence your judgments and decisions.",
  "instructions_mission_header":"what is the owner(s) vision?",
  "instructions_mission_help":"Describe your vision. A vision can be defined as an image of a future, or a desired state. Here you can enter what the owners want the company to be, if they get it just as they please.",
  "instructions_mission_placeholder":"Describe your vision. A vision can be defined as an image of a future, or a desired state. Here you can enter what the owners want the company to be, if they get it just as they please.",
  "instructions_objectives_header":"what is the owner(s) objectives?",
  "instructions_objectives_help":"Here you can insert the owners more specific goals. Do they want to sell the company at a time? Do they want to be left with a certain amount of money? Do they have goals that have nothing to do with money?",
  "instructions_objectives_placeholder":"Here you can insert the owners more specific goals. Do they want to sell the company at a time? Do they want to be left with a certain amount of money? Do they have goals that have nothing to do with money?",
  "instructions_restrictions_header":"what restrictions does the owner(s)?",
  "instructions_restrictions_help":"What will you as owner(s) under no circumstances will allow the company to do? Move the company to another country? Take out a loan? Do business with a particular country or organization?",
  "instructions_restrictions_placeholder":"What will you as owner(s) under no circumstances will allow the company to do? Move the company to another country? Take out a loan? Do business with a particular country or organization?",
  "instructions_informing_header":"how does the owner(s) want to be informed?",
  "instructions_informing_help":"Describe how the owner(s) want to be informed about the progress of the company? What do they want to know? How often do they want to be informed, and in what way?",
  "instructions_informing_placeholder":"Describe how the owner(s) want to be informed about the progress of the company? What do they want to know? How often do they want to be informed, and in what way?",
  "resources_header":"Resources",
  "resources_subheader":"Before you start making or evaluating your business idea, you should take an inventory over the resources you already have. Remember, you\"re not allowed to add resources that you \"almost\" have. You don\"t have to fill in all the boxes. You can always came back here and add to it later.",
  "resources_employees_header":"employees",
  "resources_employees_help":"Insert the people that are already employed in your company, what skills and knowledge do they have that are important to you, and what do they cost? If you have many employees, describe them per department or group. Register a fixed monthly salary or specify salary per month If you don’t want this employee to be included in the project, just turn the switch over to “off”.",
  "resources_employees_placeholder":"Insert the people that are already employed in your company, what skills and knowledge do they have that are important to you, and what do they cost? If you have many employees, describe them per department or group. Register a fixed monthly salary or specify salary per month If you don’t want this employee to be included in the project, just turn the switch over to “off”.",
  "resources_partners_header":"partners & advisors",
  "resources_partners_help":"Insert the partners and advisors that you already have a relationship with. Add the skills and knowledge they have that are important to you, and what they cost? If their cost varies from month to month, select differentiated cost. If you don’t want this partner to be included in the project, just turn the switch over to “off”.",
  "resources_partners_placeholder":"Insert the partners and advisors that you already have a relationship with. Add the skills and knowledge they have that are important to you, and what they cost? If their cost varies from month to month, select differentiated cost. If you don’t want this partner to be included in the project, just turn the switch over to “off”.",
  "resources_patents_header":"patents & ipr\"s",
  "resources_patents_help":"Create a sticky for each patent or registered right. Enter any costs for the management of these, in the appropriate month. Switch the note to \"off\" to remove it from your project calculations.",
  "resources_patents_placeholder":"Create a sticky for each patent or registered right. Enter any costs for the management of these, in the appropriate month. Switch the note to \"off\" to remove it from your project calculations.",
  "resources_products_header":"products & services",
  "resources_products_help":"Add a sticky not for any products or services that you already have, or that will be completed in the project period. Do not register any products or services that you want to create in the future as these belong in the goal board.",
  "resources_products_placeholder":"Add a sticky not for any products or services that you already have, or that will be completed in the project period. Do not register any products or services that you want to create in the future as these belong in the goal board.",
  "resources_accounts_header":"cash & credit",
  "resources_accounts_help":"Create a sticky for each bank account, loan or overdraft fascility you have at the beginning of your project period. Enter the amount of money/ credit you have available at the start of the period. Turn the note \"off\" to remove it from further project calculations. These notes will be used in your cash-flow prognosis.",
  "resources_accounts_placeholder":"Create a sticky for each bank account, loan or overdraft fascility you have at the beginning of your project period. Enter the amount of money/ credit you have available at the start of the period. Turn the note \"off\" to remove it from further project calculations. These notes will be used in your cash-flow prognosis.",
  "resources_buildings_header":"buildings & rental contracts",
  "resources_buildings_help":"Add a note for each building or lease contract that you have. Add your rent costs or operating costs for each of these. Select fixed monthly cost or specify cost per month to distribute the costs to the relevant month(s). If you want to exclude the note from project tasks and calculations, just switch it \"off\".",
  "resources_buildings_placeholder":"Add a note for each building or lease contract that you have. Add your rent costs or operating costs for each of these. Select fixed monthly cost or specify cost per month to distribute the costs to the relevant month(s). If you want to exclude the note from project tasks and calculations, just switch it \"off\".",
  "resources_machines_header":"machines & equipment",
  "resources_machines_help":"Add a note for each machine, vehicle or major piece of equipment that you have in your company. Add rent costs or operating costs for each of these, either as a fixed cost per month or specify the cost on the relevant months. If you want to take the note out of the case study, just switch it \"off\".",
  "resources_machines_placeholder":"Add a note for each machine, vehicle or major piece of equipment that you have in your company. Add rent costs or operating costs for each of these, either as a fixed cost per month or specify the cost on the relevant months. If you want to take the note out of the case study, just switch it \"off\".",
  "resources_contracts_header":"customer contracts",
  "resources_contracts_help":"If you have existing customer contracts that give either fixed subscription revenue in the period, or a contracted delivery or payment period, you can register them here. Make a note of each contract and register the expected income in the correct month or months. Put a check in the box for the correct product or service.",
  "resources_contracts_placeholder":"If you have existing customer contracts that give either fixed subscription revenue in the period, or a contracted delivery or payment period, you can register them here. Make a note of each contract and register the expected income in the correct month or months. Put a check in the box for the correct product or service.",
  "resources_fixed-cost_lbl":"Fixed monthly cost",
  "resources_var-cost_lbl":"Variable cost pr month",
  "resources_fixed-salary_lbl":"Fixed monthly salary",
  "resources_var-salary_lbl":"Variable salary pr month",
  "resources_fixed-fee_lbl":"Fixed monthly fee",
  "resources_var-fee_lbl":"Variable fee pr month",
  "resources_fixed-revenue_lbl":"Fixed monthly revenue",
  "resources_var-revenue_lbl":"Variable revenue pr month",
  "fixed_salary_opt":"Fixed monthly cost",
  "month_salary_opt":"Specify cost per month",
  "own_directive":"own directive",
  "month_revenue_opt":"Fixed monthly revenue",
  "fixed_revenue_opt":"Specify revenue per month",
  "money_cash_opt":"cash",
  "money_overdraft_opt":"available overdraft",
  "money_loan_opt":"available loan",
  "button_ok": "Ok",
  "button_next": "Next",
  "gaps_1x1_help": "Do you wanna add some of your competitors? (if you have more than three, you should group them together)",
  "gaps_1x1_help_header": "Add competitors",
  "gaps_1x2_help_header": "Start with your own gaps?",
  "gaps_1x2_help": "Click OK to start on your own strength and weaknesses, or go straight to objectives.",
  "gaps_1x1_placeholder": "Give the competitor name!",
  "gaps_1x2_placeholder": "Max 3 competitors",
  "gaps_2x1_help": "Now you can add strengths or weaknesses for yourself and for your competitors.",
  "gaps_3x1_help": "The most important of your weaknesses and the competitors strengths can be prioritized as gaps by pressing the \"gap\" button.",
  "label_model_sticky": "Business model sticky",
  "label_gap_t_strength": "Strength",
  "label_gap_t_weakness": "Weakness",
  "idea_header":"Business idea",
  "idea_subheader":"The business idea is the core of your company. You should focus on what value you could create for your customers. Gather your colleagues and be creative. Make as many suggestions as you can.",
  "ideaItems_uniqueness_header":"What makes you unique?",
  "ideaItems_uniqueness_help":"Here you should add what make you better suited to solve the problem than anyone else. Why should the customer choose you? What will make it difficult for the competition to copy you? Add as many stickies as you need. One uniqueness can relate to one problem, or to many.",
  "ideaItems_uniqueness_placeholder":"Here you should add what make you better suited to solve the problem than anyone else. Why should the customer choose you? What will make it difficult for the competition to copy you? Add as many stickies as you need. One uniqueness can relate to one problem, or to many.",
  "ideaItems_problem_header":"What problem do you solve?",
  "ideaItems_problem_help":"People are usually willing to pay good money if you solve a problem for them. Given your uniqueness and resources; what problem can you solve? Try to be creative and let the wild ideas flow.",
  "ideaItems_problem_placeholder":"People are usually willing to pay good money if you solve a problem for them. Given your uniqueness and resources; what problem can you solve? Try to be creative and let the wild ideas flow.",
  "ideaItems_audience_header":"Who will have this problem?",
  "ideaItems_audience_help":"No point in solving problem if you do not know who has them. Try to think of the possible target groups for all imaginable problems solved by yours uniqueness. Don\"t make target groups to wide and generic. It\"s so much easier to reach out to a small and clearly defined groups.",
  "ideaItems_audience_placeholder":"No point in solving problem if you do not know who has them. Try to think of the possible target groups for all imaginable problems solved by yours uniqueness. Don\"t make target groups to wide and generic. It\"s so much easier to reach out to a small and clearly defined groups.",
  "ideas_help-1_header": "Create as many stickies as you like",
  "ideas_help-1_content": "Create stickies by clicking on the plus. You can merge stickies by dragging them on top of each other. You need to have at least one sticky in each box.",
  "ideas_help-2_header": "Done creating stickies?",
  "ideas_help-2_content": "Start linking the stickies into business ideas by clicking the chain-button! You need at least one sticky from each of the three boxes.",
  "ideas_help-3_header": "Name your first business idea!",
  "ideas_help-3_content": "You have one sticky from each box. If that is all you want, give the first business idea a name!",
  "ideas_help-4_header": "Done making business ideas for now?",
  "ideas_help-4_content": "If you\"re all out of ideas, you have to decide whether you want to test any of the ideas, or if you want to start developing each idea into business models.",
  "business_idea_count":"{{ideasCount}} business ideas",
  "business_model_count":"{{modelsCount}} business models",
  "canvas__obj-header":"{{objectivesCount}} objectives",
  "ideaItems_3x1_placeholder": "Give the idea name!",
  "idea_button_business_model": "Business model",
  "idea_button_test": "Test",
  "obj_header":"Objectives",
  "obj_subheader":"Set objectives for your company. In that way you can be sure that everyone knows what the priorities are.",
  "objectives_competence_header":"competence",
  "objectives_competence_help":"Do you need new competence to reach your objectives? Should you hire new people? Does anybody need training or certifying?",
  "objectives_competence_placeholder":"Is there lacks of competence in your company? Do you need new employees?",
  "objectives_solution_header":"products and services",
  "objectives_solution_help":"Should you build new products or services? Do you need to improve the existing ones?",
  "objectives_solution_placeholder":"What objectives do you have for solutions that you will deliver?",
  "objectives_sales_header":"sales and marketing",
  "objectives_sales_help":"How much do you plan to sell of each product? Do you have any marketing objectives?",
  "objectives_sales_placeholder":"How much should you sell?",
  "objectives_finances_header":"financial",
  "objectives_finances_help":"Do you need to raise or loan money? Is there any kind of grant you will apply for?",
  "objectives_finances_placeholder":"Revenue",
  "objective_list":"Objective list",
  "objectives_help-1_header":"Objectives pr month",
  "objectives_help-1_content":"As you define your objectives, they will pop up here. You can categorize the objectives into milestones, numeric objectives, one-time sales, subscription sales or loan or equity. You can divide the objective over each month of the plan, and you can divide the objectives into sub-objectives.",
  "tasks_header":"Tasks",
  "tasks_subheader":"Tasks are the core of what you do every day. Keep up to date on what the entire team does.",
  "tasks_todo":"Queue",
  "tasks_todo_help":"Help text",
  "monthly_tasks":"Monthly tasks",
  "monthly_tasks_help":"Help text",
  "tasks_objs_header":"Objectives",
  "tasks_objs_help":"Help text",
  "tasks_test_header":"Tests",
  "tasks_test_help":"Help text",
  "tasks_gaps_header":"Gaps",
  "tasks_gaps_help":"Help text",
  "tasks_risks_header":"Risks",
  "tasks_risks_help":"Help text",
  "gaps_header":"Gaps",
  "gaps_subheader":"Compared to your competitors, what is your strengths and weaknesses? Then turn the table. What is your competitors strengths and weaknesses? Remember to always to evaluate based on your chosen business idea and model. Remember, you can always revisit this board and add stuff.",
  "button_objectives":"Objectives",
  "comp_box_my_helptext":"In this box, you can enter the strengths and weaknesses that you have in each of your business model element. Try consider the difference between the situation you want to have and the situation you really are in, right now. Also consider whether you are better or worse than your competitors.",
  "comp_box_other_helptext":"What strengths and weaknesses does {{name}} have? Remember to only add those who are relevent for this business model.",
  "comp_dialog_header":"Competitor or group of competitors",
  "registration_message_idea":"To save your idea you must create a case.",
  "registration_message_instructions":"To save owners instructions you must create a case."
}/*stopJson*/;
