/*startJson*/var locale_en = {
  "lean_business_builder": "Lean business builder",
  "canvas_header":"Lean business builder",
  "canvas_subheader":"Do you want to start a company, or just play around with some ideas? Start here!",
  "button_save": "Save",
  "tasks": "Tasks",
  "business_idea": "Business Idea",
  "gap": "GAP",
  "objectives": "Objectives",
  "business_model": "Business Model",
  "overview": "Overview",
  "resources": "Resources",
  "risks": "Risks",
  "title":"Title",
  "good_luck":"Good luck!",
  "label_idea_name": "idea name",
  "label_task_name": "Name of the task",
  "label_activity_name": "Name of the activity",
  "label_associated": "Associated",
  "label_status": "Status",
  "label_description": "Description",
  "label_responsible": "Responsible",
  "label_due_month": "Due month",
  "label_costgroup": "Cost group",
  "label_gap_name":"Name of gap",
  "label_obj_name":"Name of the objective",
  "label_risk_name":"Name of the risk",
  "label_objtype":"Objective type",
  "label_sum":"Sum",
  "label_cost":"Cost",
  "label_consequence":"Consequence",
  "label_probability": "Probability",
  "label_model_name": "Sticky title",
  "canvas_message_1":"You will build a business or just test out business ideas?",
  "canvas_message_2":"Need board a see what you are doing? Start here!",
  "done":"Done",
  "save":"Save",
  "business_ideas":"Business ideas",
  "model_header":"Business models",
  "model_subheader":"The business idea tell you what you should regarding your business. The business model will tell you how you should do it."
}/*stopJson*/;
